networks:
  php-swoole:
    driver: bridge
services:
  php-cli:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-cli
    volumes:
      - .:/var/www
    tty: true
    ports:
      - "9000:9000"
    networks:
      - php-swoole
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php-cli
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-swoole